### ISSUE TITLE
code textのとき色を変えたい

### ISSUE THREAD

**Issue by kanehis** [kanehis/dokuwiki#7]
一例
```css
.code.text {
    background-color: initial;
    box-shadow: none;
    border: none;
}
```
